package main

// DO NOT EDIT, this file is generated by hover at compile-time for the flutter_zmq plugin.

import (
	flutter "github.com/go-flutter-desktop/go-flutter"
	flutter_zmq "github.com/dolaned/flutter_zmq/go"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(&flutter_zmq.FlutterZmqPlugin{}))
}
